import "@/app/globals.css";
import Script from "next/script";
import Providers from "@/app/providers";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Montserrat({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        src="https://kit.fontawesome.com/ec69ef3ca4.js"
        crossOrigin="anonymous"
      />
      <body className={`${inter.className} h-screen flex flex-col`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
